config/routes.rb
ExternalFulfillment::Application.routes.draw do

  root :to => 'home#index'

  devise_for :users,:controllers => {
      :registrations => "registrations" ,
      :invitations => 'invitations'
  }
  resources :vendors do
    get :edit_questionnaire
    post :update_questionnaire
    post :search,:on => :collection
  end
  resources :carriers
  resources :uploaded_files, :only => [:create,:new,:index,:destroy]
  resources :users
  resources :warehouses
  resources :vendor_questions do
    put :sort, :on => :collection
  end
  resources :invitation_messages
  resources :contacts

end

app/models/vendor_question.rb
class VendorQuestion < ActiveRecord::Base

  attr_accessible :options, :question, :section, :question_type,:position

  validates_presence_of :question,:section,:question_type
  validates_presence_of :options, :if => Proc.new {|q| q.multiple_answer? || q.multiple_choice?}


  SECTIONS = {"General Information" => "General","Logistics" => "Logistics"}
  TYPES = {"Multiple Choice" => "multiple_choice","Text" => "text","Multiple Answer" => "multiple_answer"}

  has_many :answers, :dependent => :destroy
  has_many :vendors, :through => :answers

  default_scope order('position ASC')
  scope :general_information, where(:section => VendorQuestion::SECTIONS["General Information"])
  scope :logistics, where(:section => VendorQuestion::SECTIONS["Logistics"])

  acts_as_list :scope => 'section = \'#{section}\''

  after_create :create_answers, :set_position

  def multiple_choice?
    self.question_type.eql?("multiple_choice")
  end

  def multiple_answer?
    self.question_type.eql?("multiple_answer")
  end

  def options_array
    self.options.split(",")
  end

  def create_answers
   Vendor.all.each do |v|
      Answer.create({:vendor_question_id => self.id,:vendor_id => v.id})
    end
  end

  def set_position
    self.move_to_bottom
  end

end

app/controllers/vendor_questions_controller.rb
class VendorQuestionsController < ApplicationController
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Vendor Questions",:vendor_questions_path

  def index
    permitted_to! :read, :vendor_questions
    @general_information = VendorQuestion.general_information
    @logistics = VendorQuestion.logistics
    flash.now[:notice] = "You can drag and drop the questions to sort them!"
  end

  def new
    permitted_to! :new, :vendor_question
    @vendor_question =  VendorQuestion.new
    add_breadcrumb "New Vendor Question", :new_vendor_question_path
  end

  def create
    permitted_to! :create, :vendor_question
    @vendor_question = VendorQuestion.new(params[:vendor_question])
    if @vendor_question.save
      flash[:success] = "Vendor Question created successfully"
      redirect_to vendor_questions_path
    else
      render :new
    end

  end

  def edit
    @vendor_question = VendorQuestion.find(params[:id])
    permitted_to! :edit, @vendor_question
    add_breadcrumb @vendor_question.question, :edit_vendor_question_path

  end

  def update
    @vendor_question = VendorQuestion.find(params[:id])
    permitted_to! :update, @vendor_question
    if @vendor_question.update_attributes(params[:vendor_question])
      flash[:success] = "Vendor Question updated successfully"
      redirect_to vendor_questions_path
    else
      render :edit
    end
  end

  def sort
    @vendor_question = VendorQuestion.find(params[:id])
    @vendor_question.update_attribute(:position,params[:position])
    render :json => "success"
  end

  def destroy
    @vendor_question = VendorQuestion.find(params[:id])
    @vendor_question.destroy
    flash[:success] = "Vendor Question deleted successfully"
    redirect_to vendor_questions_path
  end

end

app/helpers/vendor_questions_helper.rb
module VendorQuestionsHelper
end

app/views/vendor_questions/_form.html.haml
= simple_form_for @vendor_question do |f|
 = f.input :question,:required => true,:input_html => {:rows => 1 }
 = f.input :question_type,:as => :select, :collection => VendorQuestion::TYPES.map{|k,v| [k.to_s,v]},:required => true
 = f.input :section,:as => :select,:collection => VendorQuestion::SECTIONS,:required => true
 = f.input :options,:hint => "Enter comma separated values for Multiple choice question"
 = f.submit

app/views/vendor_questions/edit.html.haml
= render :partial => "form"

app/views/vendor_questions/index.html.haml
.row
  .col-md-4.col-md-offset-10
    - if permitted_to? :new,:vendor_questions
      = link_to "<span class='glyphicon glyphicon-plus'></span>".html_safe, new_vendor_question_path,:class => "btn btn-success"
%ul.nav.nav-tabs#tabs{role: "tablist"}
  %li.active
    %a{"data-toggle" => "tab", href: "#general_information", role: "tab"} General Information
  %li
    %a{"data-toggle" => "tab", href: "#logistics", role: "tab"} Logistics
.tab-content
  #general_information.tab-pane.active.sortable
    .row
      .col-md-12
        %br
          %table.table.table-striped.table-hover#sortable
            %tr
              %th ID
              %th Question
              %th Type
              %th
            - @general_information.each do |question|
              %tr(data-id="#{question.id}")
                %td= question.id
                %td= link_to truncate(question.question,:length => 45), edit_vendor_question_path(question.id)
                %td= question.question_type
                %td= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe,vendor_question_path(:id => question.id),:method => :delete,:confirm => "Are you sure you want to delete this question?",:class => "btn btn-danger"
  #logistics.tab-pane.sortable
    .row
      .col-md-12
        %br
          %table.table.table-striped.table-hover#sortable
            %tr
              %th ID
              %th Question
              %th Type
              %th
            - @logistics.each do |question|
              %tr(data-id="#{question.id}")
                %td= question.id
                %td= link_to truncate(question.question,:length => 45), edit_vendor_question_path(question.id)
                %td= question.question_type
                %td= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe,vendor_question_path(:id => question.id),:method => :delete,:confirm => "Are you sure you want to delete this question?",:class => "btn btn-danger"
:javascript
  $(function() {
      var fixHelper = function(e, ui) {
      	ui.children().each(function() {
      		$(this).width($(this).width());
      	});
      	return ui;
      };
      function positionUpdated(e,ui){
        $.ajax({
          type: "PUT",
          contentType: "application/json; charset=utf-8",
          url:"#{sort_vendor_questions_path}",
          data: JSON.stringify({id:ui.item.data("id"),position:ui.item.index()}),
          dataType: "json"
        });
      };
      $(".sortable tbody").sortable({
      	helper: fixHelper,
        update: positionUpdated
      }).disableSelection();
    });

app/views/vendor_questions/new.html.haml
= render :partial => "form"