config/routes.rb
ExternalFulfillment::Application.routes.draw do

  root :to => 'home#index'

  devise_for :users,:controllers => {
      :registrations => "registrations" ,
      :invitations => 'invitations'
  }
  resources :vendors do
    get :edit_questionnaire
    post :update_questionnaire
    post :search,:on => :collection
  end
  resources :carriers
  resources :uploaded_files, :only => [:create,:new,:index,:destroy]
  resources :users
  resources :warehouses
  resources :vendor_questions do
    put :sort, :on => :collection
  end
  resources :invitation_messages
  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :item,:polymorphic => true
  attr_accessible :email, :name, :phone,:item_id,:item_type,:role

  validates_presence_of :name,:email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i , :message => "Please enter a valid email"
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  add_breadcrumb "Home", :root_path
  def new
    @contact = Contact.new
    @item = params[:item_type].constantize.find(params[:item_id])
    @contact.item = @item
    add_breadcrumb @contact.item_type + "s", Proc.new {|u| get_index_path(@item)}
    add_breadcrumb @item.company_name,Proc.new {|u| get_path(@item)}
    add_breadcrumb "New Contact",:new_contact_path
    permitted_to! :new, @contact
  end

  def create
    @contact = Contact.new(params[:contact])
    permitted_to! :create, @contact
    if @contact.save
      flash[:success]= "Contact created successfully"
      if @contact.item_type.eql?(Carrier.name)
        redirect_to carrier_path(@contact.item_id)
      elsif @contact.item_type.eql?(Vendor.name)
        redirect_to vendor_path(:id => @contact.item_id,:anchor => "contacts")
      end
    else
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
    permitted_to! :edit, @contact
    add_breadcrumb @contact.item_type+ "s", Proc.new {|u| get_index_path(@contact.item)}
    add_breadcrumb @contact.item.company_name,Proc.new {|u| get_path(@contact.item)}
    add_breadcrumb "Edit Contact",:edit_contact_path
  end

  def update
    @contact = Contact.find(params[:id])
    permitted_to! :update, @contact
    if @contact.update_attributes(params[:contact])
      flash[:success]= "Contact updated successfully"
      if @contact.item_type.eql?(Carrier.name)
        redirect_to carrier_path(@contact.item_id)
      elsif @contact.item_type.eql?(Vendor.name)
        redirect_to vendor_path(:id => @contact.item_id,:anchor => "contacts")
      end
    else
      render :edit
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    permitted_to! :delete,@contact
    @item_type = @contact.item_type
    @item_id = @contact.item_id
    @contact.destroy
    flash[:success]= "Contact removed successfully"
    if @item_type.eql?(Carrier.name)
      redirect_to carrier_path(:id => @item_id)
    elsif @item_type.eql?(Vendor.name)
      redirect_to vendor_path(:id => @item_id,:anchor => "contacts")
    end
  end

  private

  def get_path(item)
    if item.is_a?(Vendor)
      return vendor_path(:id => item.id)
    else
      return carrier_path(:id => item.id)
    end
  end
  def get_index_path(item)
    if item.is_a?(Vendor)
      return vendors_path
    else
      return carriers_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.haml
= simple_form_for @contact do |f|
  = f.input :name,:required => true
  = f.input :email,:as => :email,:required => true
  = f.input :phone
  = f.input :role
  - if @contact.new_record?
    = f.input :item_type,:as => :hidden
    = f.input :item_id  ,:as => :hidden
  = f.submit "Save",:class =>"btn btn-success"

app/views/contacts/_show.html.haml
.row.contact
  .col-md-8
    %p
      = "Name: #{contact.name}"
    %p
      = "Email: #{contact.email}"
    %p
      = "Phone: #{contact.phone}"
    %p
      = "Role: #{contact.role}"
  .col-md-2.col-md-offset-2
    - if permitted_to? :edit, contact
      =link_to "<span class='glyphicon glyphicon-edit'></span>".html_safe,edit_contact_path(:id => contact.id),:class => "btn btn-warning"
    - if permitted_to? :delete, contact
      = link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe,contact_path(:id => contact.id),:method => :delete,:confirm => "Are you sure you want to delete this contact ?",:class => "btn btn-danger"

app/views/contacts/edit.html.haml
=render :partial => 'form'

app/views/contacts/new.html.haml
=render :partial => 'form'