config/routes.rb
ExternalFulfillment::Application.routes.draw do

  root :to => 'home#index'

  devise_for :users,:controllers => {
      :registrations => "registrations" ,
      :invitations => 'invitations'
  }
  resources :vendors do
    get :edit_questionnaire
    post :update_questionnaire
    post :search,:on => :collection
  end
  resources :carriers
  resources :uploaded_files, :only => [:create,:new,:index,:destroy]
  resources :users
  resources :warehouses
  resources :vendor_questions do
    put :sort, :on => :collection
  end
  resources :invitation_messages
  resources :contacts

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

  attr_accessible :company_name, :payment_terms,:vendor_code, :answers_attributes,:managed_by_id,:street,:city,:postcode,:country,:carrier_comment

  validates_presence_of :vendor_code,:company_name

  belongs_to :user
  belongs_to :managed_by, :class_name => "User"

  has_many :uploaded_file_on_items,:as => :item
  has_many :uploaded_files,:through => :uploaded_file_on_items

  has_many :warehouses

  has_many :answers
  has_many :vendor_questions,:through => :answers,:order => "position ASC"

  has_many :contacts,:as => :item

  accepts_nested_attributes_for :answers


  default_scope where(:deleted_at => nil)

  after_create :create_answers

  def create_answers
    VendorQuestion.all.each do |vq|
      Answer.create({:vendor_question_id => vq.id,:vendor_id => self.id})
    end
  end

  def self.search(word)
    where("company_name LIKE ? or vendor_code LIKE ?","%#{word}%","%#{word}%")
  end

  def status
    if self.user.invitation_token.present?
      return "Invitation sent"
    elsif self.user.invitation_accepted_at.present?
      return "Registration Done"
    else
      return "Integration in Progress"
    end
  end

  def general_questions
    self.vendor_questions.general_information.includes(:answers).joins(:answers)
  end

  def logistics_questions
    self.vendor_questions.logistics.includes(:answers).joins(:answers)
  end

  self.per_page = 20

end

app/controllers/vendors_controller.rb
require 'csv'
class VendorsController < ApplicationController
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Vendors",:vendors_path, :if => Proc.new {|p| permitted_to? :index,:vendors}
  before_filter :authenticate_user!

  layout 'application'

  def index
    permitted_to! :index, :vendors
    respond_to do |format|
      format.html do
        @vendors = Vendor.page(params[:page])
      end
      format.csv do
        @vendors = Vendor.find(params[:ids])
        headers['Content-Disposition'] = "attachment; filename=\"vendor-list\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def edit
    @vendor = Vendor.find(params[:id])
    permitted_to! :edit, @vendor
    add_breadcrumb @vendor.company_name,:vendor_path
    add_breadcrumb "Edit",:edit_vendor_path
  end

  def update
    @vendor = Vendor.find(params[:id])
    if current_user.carrier?
      permitted_to! :post_comment_to_vendor, @vendor
      @params = update_carrier_comments
    else
      permitted_to! :update, @vendor
      @params = params[:vendor]
    end

    respond_to do |format|
      if @vendor.update_attributes(@params)
        format.html do
          flash[:success] = "Vendor updated successfully"
          redirect_to vendor_path(@vendor.id)
        end
        format.json do
          render :json => true
        end
      else
        format.html do
          render :edit
        end
        format.json do
          render :json => "error"
        end
      end
    end
  end

  def show
    if params[:id].present?
      @vendor = Vendor.find(params[:id])
    else
      @vendor = current_user.vendor
    end
    permitted_to! :show, @vendor
    add_breadcrumb @vendor.company_name,:vendor_path
    @general_questions = @vendor.general_questions
    @logistics_questions = @vendor.logistics_questions
    @vendor_files = UploadedFile.vendor_files
    respond_to do |format|
      format.html
      format.xls do
        headers['Content-Disposition'] = "attachment; filename=\"#{@vendor.company_name}.xls\""
        headers['Content-Type'] ||= 'application/xls'
      end
    end

  end

  def edit_questionnaire
    @vendor = Vendor.find(params[:vendor_id])
    @section = VendorQuestion::SECTIONS[params[:section]]
    @answers = @vendor.answers.includes(:vendor_question).joins(:vendor_question).where("vendor_questions.section in (?)", @section).order("position ASC")
    permitted_to! :edit, @vendor
    add_breadcrumb @vendor.company_name,Proc.new {|c| vendor_path(:id => @vendor.id)}
    add_breadcrumb params[:section],:vendor_edit_questionnaire_path
  end

  def search
    permitted_to! :index, :vendors
    @search = params[:vendor][:word]
    @vendors = Vendor.search(@search).page(params[:page])
    render :index
  end

  def update_questionnaire
    @vendor = Vendor.find(params[:vendor_id])
    @section = params[:section]
    permitted_to! :update, @vendor
    if @vendor.update_attributes(params[:vendor])
      redirect_to vendor_path(@vendor,:anchor => @section)
    else
      render :edit_questionnaire
    end
  end

  def destroy
    @vendor = Vendor.find(params[:id])
    permitted_to! :destroy, @vendor
    @vendor.update_attribute(:deleted_at,Time.now)
    @vendor.user.destroy
    flash[:success] = "Vendor removed successfully"
    redirect_to vendors_path
  end

  def update_carrier_comments
    params.require(:vendor).permit(:carrier_comment)
  end

end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.haml
.row
  .col-md-12
    = simple_form_for(@vendor, :html => {:class => 'form-horizontal' }) do |f|
      =f.input :company_name,:required => true
      =f.input :vendor_code,:required => true
      =f.input :payment_terms,:required => true
      = f.input :street
      = f.input :city
      = f.input :postcode
      = f.input :country
      = f.submit "save",:class => "btn btn-success"
      = link_to "cancel", vendor_path(@vendor.id),:class => "btn btn-default"

app/views/vendors/edit.html.haml
=render :partial => 'form'

app/views/vendors/edit_questionnaire.html.haml
=simple_form_for @vendor,:url => vendor_update_questionnaire_path(:vendor_id => @vendor.id), :html => {:method => :post,:class => "form-inline"}  do |f|
  = hidden_field_tag :section,@section
  = f.simple_fields_for :answers,@answers do |builder|
    = builder.object.vendor_question.question
    - if builder.object.vendor_question.multiple_choice?
      = builder.input :answer ,:as => :radio_buttons,:collection => builder.object.vendor_question.options_array,:item_wrapper_class => 'inline',:label => false
    - elsif builder.object.vendor_question.multiple_answer?
      = builder.input :answer ,:as => :check_boxes,:collection => builder.object.vendor_question.options_array,:item_wrapper_class => 'inline',:label => false
    - else
      = builder.input :answer,:input_html => {:rows => 1},:label =>false
  = f.submit

app/views/vendors/index.csv.erb
<%- headers = ['ID','Name', 'Email','Managed By','Status'] -%>
<%= CSV.generate_line headers %>
<%- @vendors.each do |vendor| -%>
    <%= CSV.generate_line([vendor.id,vendor.company_name,vendor.vendor_code,vendor.managed_by.name,vendor.status]) %>
<%- end -%>

app/views/vendors/index.html.haml
.row

  = simple_form_for :vendor,:url => search_vendors_path,:html => {:class => "form-search vendor-search-form"} do |f|
    = f.input_field :word,:required => false,:class => "search-query input-medium",:placeholder => "Search",:value => @search
    = link_to "<span class='glyphicon glyphicon-search'></span>".html_safe,"#",:class => "btn btn-primary",:onclick => "$(this).closest('form').submit();"
    = link_to "<span class='glyphicon glyphicon-refresh'></span>".html_safe,vendors_path,:class => "btn btn-default"
    = link_to "<span class='glyphicon glyphicon-download-alt'>CSV</span>".html_safe, vendors_path(:format => :csv,:ids => @vendors.collect(&:id)),:class => "btn btn-success"

.row
  .col-md-12
    %br
      %table.table.table-striped.table-hover
        %tr
          %th ID
          %th Vendor Code
          %th Name
          %th Managed by
          %th Status
          %th Registration Date
          - if current_user.carrier? or current_user.has_admin_role?
            %th Carrier Comment
          %th

        - @vendors.each do |vendor|
          %tr
            %td= vendor.id
            %td= vendor.vendor_code
            %td= link_to vendor.company_name,vendor_path(vendor.id)
            %td= vendor.managed_by.name
            %td= vendor.status
            %td
              - if vendor.user.invitation_accepted_at
                = vendor.user.invitation_accepted_at.to_date
            - if current_user.carrier? or current_user.has_admin_role?
              %td
                %a.editable(data-name="carrier_comment" data-type="text" data-pk="#{vendor.id}" data-url="#{vendor_path(:id => vendor.id)}" data-resource="vendor" data-title="Enter username")
                  =vendor.carrier_comment
            %td
              = link_to "<span class='glyphicon glyphicon-download-alt'></span>".html_safe,vendor_path(:id => vendor.id,:format => :xls),:class => "btn btn-success"

= will_paginate @vendors
:javascript
  $(function(){
    $.fn.editable.defaults.mode = 'inline';
    $('.editable').editable();
  });

app/views/vendors/show.html.haml
.row
  .col-md-3
    %h2= @vendor.company_name
  .col-md-2.col-md-offset-7
    = link_to "<span class='glyphicon glyphicon-download-alt'></span>".html_safe,vendor_path(:id => @vendor.id,:format => :xls),:class => "btn btn-success"
    - if permitted_to? :delete, @vendor
      =link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe,vendor_path(:id => @vendor.id),:method => :delete,:confirm => "Are you sure you want to delete this Vendor?",:class => "btn btn-danger"
/ Nav tabs
%ul.nav.nav-tabs#tabs{role: "tablist"}
  %li.active
    %a{"data-toggle" => "tab", href: "#vendor", role: "tab"} Vendor
  %li
    %a{"data-toggle" => "tab", href: "#contacts", role: "tab"} Contacts
  %li
    %a{"data-toggle" => "tab", href: "##{VendorQuestion::SECTIONS['General Information']}", role: "tab"} General Information
  %li
    %a{"data-toggle" => "tab", href: "##{VendorQuestion::SECTIONS['Logistics']}", role: "tab"} Logistics Information
  %li
    %a{"data-toggle" => "tab", href: "#warehouses", role: "tab"} Warehouses
  - unless current_user.carrier?
    %li
      %a{"data-toggle" => "tab", href: "#uploaded_files", role: "tab"} Uploaded Files
    %li
      %a{"data-toggle" => "tab", href: "#upload_file", role: "tab"} Upload File
/ Tab panes
.tab-content
  #vendor.tab-pane.active
    - if permitted_to? :edit, @vendor
      .row
        .col-md-2.col-md-offset-10
          =link_to "<span class='glyphicon glyphicon-edit'></span>".html_safe, edit_vendor_path(@vendor.id),:class => "btn btn-warning"
    .row
      .col-md-6
        %h4
          Company Info
        %p
          = "Company Name: #{@vendor.company_name}"
        %p
          = "Vendor Code: #{@vendor.vendor_code}"
        %p
          = "Payment Terms: #{@vendor.payment_terms}"
      .col-md-6
        %h4 Address
        %p
          = "Street: #{@vendor.street}"
        %p
          = "City: #{@vendor.city}"
        %p
          = "Postal Code: #{@vendor.postcode}"
        %p
          = "Country: #{@vendor.country}"
  #contacts.tab-pane
    .row
      .col-md-3
        %h2 Contacts
      .col-md-2.col-md-offset-7
        - if permitted_to? :update,@vendor
          =link_to "<span class='glyphicon glyphicon-plus'></span>".html_safe,new_contact_path(:item_id => @vendor.id,:item_type => @vendor.class),:class => "btn btn-success"

    - @vendor.contacts.each do |contact|
      = render :partial => "contacts/show",:locals => {:contact => contact}
  .tab-pane(id="#{VendorQuestion::SECTIONS['General Information']}")
    .row
      .col-md-4
        %h2 General Information
      - if permitted_to? :edit , @vendor
        .col-md-2.col-md-offset-6
          = link_to "Edit Information",vendor_edit_questionnaire_path(:vendor_id => @vendor.id,:section => "General Information"),:class => "btn btn-default"
    .row
      .col-md-12
        -@general_questions.each do |question|
          .question-box
            .question
              = question.question + " : "
            .answer.blue
              = question.answers.first[:answer]
  .tab-pane(id="#{VendorQuestion::SECTIONS['Logistics']}")
    .row
      .col-md-4
        %h2 Logistics Information
      - if permitted_to? :edit , @vendor
        .col-md-2.col-md-offset-6
          = link_to "Edit Information",vendor_edit_questionnaire_path(:vendor_id => @vendor.id,:section => "Logistics"),:class => "btn btn-default"
    .row
      .col-md-12
        -@logistics_questions.each do |question|
          .question-box
            .question
              = question.question + " : "
            .answer.blue
              = question.answers.first[:answer]
  #warehouses.tab-pane
    .row
      .col-md-3
        %h2
          Warehouses
      - if permitted_to? :create,:warehouses
        .col-md-2.col-md-offset-7
          = link_to "<span class='glyphicon glyphicon-plus'></span>".html_safe,new_warehouse_path(:vendor_id => @vendor.id),:class => "btn btn-success"
    -@vendor.warehouses.each do |warehouse|
      .warehouse
        = render :partial => "warehouses/show",:locals =>{:warehouse => warehouse}
  - unless current_user.carrier?
    #uploaded_files.tab-pane
      .row
        .col-md-6
          %h4 Files Uploaded by vendor
          %ul
          - @vendor.uploaded_files.each do |uploaded_file|
            %li
              = link_to uploaded_file.blob_file_name,uploaded_file.blob.url,:target => "_blank"
              - if permitted_to? :delete, uploaded_file
                = link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe,uploaded_file_path(:id => uploaded_file.id),:method => :delete,:confirm => "Are you sure you want to delete this file ?",:class => "btn btn-danger"
        .col-md-6
          %h4 Files uploaded by Vendor Manager
          - @vendor_files.each do |uploaded_file|
            %li
              = link_to uploaded_file.blob_file_name,uploaded_file.blob.url,:target => "_blank"
    #upload_file.tab-pane
      #uploader

  :javascript
    $(function() {

        var hash = window.location.hash;
        if(hash){
          $('#tabs a[href="' + hash + '"]').tab('show');
        }
        $("#uploader").pluploadQueue({
            // General settings
            runtimes : 'html5,flash,silverlight,html4',
            url : '#{uploaded_files_path(:item_id => @vendor.id,:item_type => "Vendor",:is_for_vendor => false)}',
            chunk_size: '1mb',
            //rename : true,
            dragdrop: true,

            filters : {
                // Maximum file size
                max_file_size : '5mb',
                // Specify what files to browse for
                mime_types: [
                    {title : "Image files", extensions : "jpg,gif,png"},
                    {title : "Doc files", extensions : "doc,docx,txt,pdf"}
                ]
            },

            //unique_names : true,
            multipart_params: {
                '#{request_forgery_protection_token}': '#{form_authenticity_token}',
                '#{request.session_options[:key]}': '#{request.session_options[:id]}',
            },
            flash_swf_url : '/plupload/Moxie.swf',
            silverlight_xap_url : '/plupload/Moxie.xap'
        });

        $('#uploader').pluploadQueue().bind('FileUploaded', function(up, file, response) {
            if (up.total.uploaded == up.files.length){
                location.reload();
            }
        });
    });

app/views/vendors/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Vendor">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Vendor Code</Data></Cell>
        <Cell><Data ss:Type="String">Payment Terms</Data></Cell>
        <Cell><Data ss:Type="String">Street</Data></Cell>
        <Cell><Data ss:Type="String">City</Data></Cell>
        <Cell><Data ss:Type="String">Postal Code</Data></Cell>
        <Cell><Data ss:Type="String">Country</Data></Cell>
      </Row>
          <Row>
            <Cell><Data ss:Type="Number"><%= @vendor.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= @vendor.company_name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= @vendor.vendor_code %></Data></Cell>
            <Cell><Data ss:Type="String"><%= @vendor.payment_terms %></Data></Cell>
            <Cell><Data ss:Type="String"><%= @vendor.street %></Data></Cell>
            <Cell><Data ss:Type="String"><%= @vendor.city %></Data></Cell>
            <Cell><Data ss:Type="String"><%= @vendor.postcode %></Data></Cell>
            <Cell><Data ss:Type="String"><%= @vendor.country %></Data></Cell>
          </Row>
    </Table>
  </Worksheet>
  <Worksheet ss:Name="Contacts">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Phone</Data></Cell>
        <Cell><Data ss:Type="String">Role</Data></Cell>
      </Row>
      <% @vendor.contacts.each do |contact|%>
        <Row>
          <Cell><Data ss:Type="String"><%= contact.name%></Data></Cell>
          <Cell><Data ss:Type="String"><%= contact.email%></Data></Cell>
          <Cell><Data ss:Type="String"><%= contact.phone%></Data></Cell>
          <Cell><Data ss:Type="String"><%= contact.role%></Data></Cell>
        </Row>
      <%end%>
    </Table>
  </Worksheet>
  <Worksheet ss:Name="General Information">
    <Table>

        <% @general_questions.each do |question| %>
          <Row>
            <Cell><Data ss:Type="String"><%= question.question%></Data></Cell>
            <Cell><Data ss:Type="String"><%= question.answers.first[:answer]%></Data></Cell>
          </Row>
        <%end%>

    </Table>
  </Worksheet>
  <Worksheet ss:Name="Logistics Information">
    <Table>

        <% @logistics_questions.each do |question| %>
          <Row>
            <Cell><Data ss:Type="String"><%= question.question%></Data></Cell>
            <Cell><Data ss:Type="String"><%= question.answers.first[:answer]%></Data></Cell>
            </Row>
        <%end%>

    </Table>
  </Worksheet>
  <Worksheet ss:Name="Warehouses">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Street</Data></Cell>
        <Cell><Data ss:Type="String">City</Data></Cell>
        <Cell><Data ss:Type="String">Postal Code</Data></Cell>
        <Cell><Data ss:Type="String">Country</Data></Cell>
        <Cell><Data ss:Type="String">Phone</Data></Cell>
        <Cell><Data ss:Type="String">Which system used for generating ship labels</Data></Cell>
        <Cell><Data ss:Type="String">Which kind of trucks are able to pickup at the warehouse</Data></Cell>
        <Cell><Data ss:Type="String">Other remarks</Data></Cell>
        <Cell><Data ss:Type="String">Height of ramps</Data></Cell>
      </Row>
      <% @vendor.warehouses.each do |warehouse| %>
        <Row>
          <Cell><Data ss:Type="String"><%= warehouse.name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= warehouse.street %></Data></Cell>
          <Cell><Data ss:Type="String"><%= warehouse.city %></Data></Cell>
          <Cell><Data ss:Type="String"><%= warehouse.postcode %></Data></Cell>
          <Cell><Data ss:Type="String"><%= warehouse.country %></Data></Cell>
          <Cell><Data ss:Type="String"><%= warehouse.phone %></Data></Cell>
          <Cell><Data ss:Type="String"><%= warehouse[:ship_label_generation] %></Data></Cell>
          <Cell><Data ss:Type="String"><%= warehouse[:pickup_trucks] %></Data></Cell>
          <Cell><Data ss:Type="String"><%= warehouse[:remarks] %></Data></Cell>
          <Cell><Data ss:Type="String"><%= warehouse.height_of_ramps %></Data></Cell>
        </Row>
      <%end%>
    </Table>
  </Worksheet>
</Workbook>