config/routes.rb
ExternalFulfillment::Application.routes.draw do

  root :to => 'home#index'

  devise_for :users,:controllers => {
      :registrations => "registrations" ,
      :invitations => 'invitations'
  }
  resources :vendors do
    get :edit_questionnaire
    post :update_questionnaire
    post :search,:on => :collection
  end
  resources :carriers
  resources :uploaded_files, :only => [:create,:new,:index,:destroy]
  resources :users
  resources :warehouses
  resources :vendor_questions do
    put :sort, :on => :collection
  end
  resources :invitation_messages
  resources :contacts

end

app/views/layouts/application.html.haml
%html
  %head
    %title ExternalFulfillment
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    - yield :head
  %body
    .container
      %nav.navbar.navbar-default(role="navigation")
        .container-fluid
          .collapse.navbar-collapse
            %ul.navbar-nav.nav
              - if permitted_to? :index, :vendors
                %li
                  =link_to "Vendors", vendors_path
              - elsif current_user and current_user.vendor? and current_user.vendor.present?
                %li
                  =link_to "My Profile", vendor_path(current_user.vendor.id)
              - if permitted_to? :index,:carriers
                %li
                  =link_to "Carriers", carriers_path
              - elsif current_user and current_user.carrier? and current_user.carrier.present?
                %li
                  =link_to "My Profile", carrier_path(current_user.carrier.id)
              - if current_user and current_user.has_admin_role?
                %li.dropdown
                  %a.dropdown-toggle(data-toggle="dropdown")
                    Admin
                    %span.caret
                  %ul.dropdown-menu(role="menu")
                    - if permitted_to? :read, :users
                      %li
                        =link_to "Users", users_path
                    - if permitted_to? :edit,:vendors
                      %li
                        =link_to "Upload Files",uploaded_files_path
                    - if permitted_to? :manage,:vendor_questions
                      %li
                        =link_to "Vendor Questions",vendor_questions_path
                    - if permitted_to? :manage,:invitation_messages
                      %li
                        =link_to "Invitation Messages",invitation_messages_path
            %ul.nav.navbar-nav.navbar-right
              - if current_user
                - if permitted_to? :invite, :users
                  %li.dropdown
                    %a.dropdown-toggle(data-toggle="dropdown")
                      Invite
                      %span.caret
                    %ul.dropdown-menu(role="menu")
                      %li
                        =link_to "Vendor", new_user_invitation_path(:role => "vendor")
                      %li
                        =link_to "Carrier",new_user_invitation_path(:role=> "carrier")
                      - if current_user.has_admin_role?
                        %li
                          =link_to "Admin",new_user_invitation_path(:role => "admin")
                %li
                  =link_to "Log out", destroy_user_session_path,:method => :delete
              - else
                %li
                  =link_to "Log in" , new_user_session_path
                -#=link_to "Sign up",new_user_registration_path,:class => "btn btn-success"
      .content
        %ol.breadcrumb
          = render_breadcrumbs :tag => :li,:separator => ""
        - unless flash.blank?
          #flash
            - flash.each do |type, message|
              -flash_type= type.eql?(:error) ? "error": type.eql?(:notice) ? "success" : "info"
              %div(class="alert-dismissible alert alert-#{flash_type}")
                %button(type="button" class="close" data-dismiss="alert")
                  %span(aria-hidden="true")
                    &times;
                    %span(class="sr-only")
                      Close
                = message
        = yield
:javascript
  $(function(){
    $('.dropdown-toggle').dropdown();
  });